In [1]:
import pandas as pd
import numpy as np
import seaborn as sb
import matplotlib.pyplot as plt

In [24]:
df = pd.read_csv("E:/Notes/DataScience/MachineLearning/Regression/car_price.csv")

In [25]:
df.head()

,selling_price,km_driven,mileage,engine,max_power,age,make,Individual,Trustmark Dealer,Diesel,Electric,LPG,Petrol,Manual,5,>5
0,1.20,120000,19.70,796.0,46.30,11.0,MARUTI,1,0,0,0,0,1,1,1,0
1,5.50,20000,18.90,1197.0,82.00,7.0,HYUNDAI,1,0,0,0,0,1,1,1,0
2,2.15,60000,17.00,1197.0,80.00,13.0,HYUNDAI,1,0,0,0,0,1,1,1,0
3,2.26,37000,20.92,998.0,67.10,11.0,MARUTI,1,0,0,0,0,1,1,1,0
4,5.70,30000,22.77,1498.0,98.59,8.0,FORD,0,0,1,0,0,0,1,1,0

In [26]:
df.groupby("make").agg("selling_price").aggregate("mean")

make
AMBASSADOR        1.452500
AUDI             17.177585
BENTLEY          20.902500
BMW              17.349017
CHEVROLET         2.723621
DAEWOO            0.780000
DATSUN            3.205176
DC               11.925000
FERRARI          20.902500
FIAT              3.152795
FORCE             5.520000
FORD              5.858258
HONDA             5.979902
HYUNDAI           5.458819
ISUZU            14.037708
JAGUAR           20.187500
JEEP             16.261890
KIA              15.731515
LAMBORGHINI      20.902500
LAND             20.560147
LEXUS            20.902500
MAHINDRA          7.315421
MARUTI            4.684721
MASERATI         20.902500
MERCEDES-AMG     20.902500
MERCEDES-BENZ    17.071479
MG               17.529474
MINI             18.529457
MITSUBISHI        8.631026
NISSAN            4.611877
OPEL              1.500000
OPELCORSA         1.516667
PORSCHE          20.866400
PREMIER           2.550000
RENAULT           4.606651
ROLLS-ROYCE      20.902500
SKODA             7.182097
TATA              4.381194
TOYOTA           10.532763
VOLKSWAGEN        5.540306
VOLVO            17.243274
Name: selling_price, dtype: float64

In [27]:
df.loc[:, "make"] = df.groupby(["make"])["selling_price"].transform("mean")  # replacing values of 'make' with the average values of corresponding model

In [29]:
df.head()

,selling_price,km_driven,mileage,engine,max_power,age,make,Individual,Trustmark Dealer,Diesel,Electric,LPG,Petrol,Manual,5,>5
0,1.20,120000,19.70,796.0,46.30,11.0,4.684721,1,0,0,0,0,1,1,1,0
1,5.50,20000,18.90,1197.0,82.00,7.0,5.458819,1,0,0,0,0,1,1,1,0
2,2.15,60000,17.00,1197.0,80.00,13.0,5.458819,1,0,0,0,0,1,1,1,0
3,2.26,37000,20.92,998.0,67.10,11.0,4.684721,1,0,0,0,0,1,1,1,0
4,5.70,30000,22.77,1498.0,98.59,8.0,5.858258,0,0,1,0,0,0,1,1,0

In [30]:
from sklearn.model_selection import train_test_split

In [32]:
y = df["selling_price"]
df.drop(columns=["selling_price"],inplace=True)

In [34]:
X_train, X_test, y_train, y_test = train_test_split(df, y, test_size=0.2, random_state=10)

In [35]:
X_train

,km_driven,mileage,engine,max_power,age,make,Individual,Trustmark Dealer,Diesel,Electric,LPG,Petrol,Manual,5,>5
19738,90000,12.99,2494.0,100.60,7.0,10.532763,0,0,1,0,0,0,1,0,1
17034,62904,28.40,1248.0,74.00,6.0,4.684721,0,0,1,0,0,0,1,1,0
17080,78368,20.77,1248.0,88.76,8.0,4.684721,0,0,1,0,0,0,1,0,1
7420,20000,20.62,1198.0,67.00,7.0,3.205176,1,0,0,0,0,1,1,0,1
15375,74000,16.80,1497.0,116.30,6.0,5.979902,0,0,0,0,0,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9372,180000,17.00,1497.0,118.00,13.0,5.979902,1,0,0,0,0,1,1,1,0
7291,37650,21.79,998.0,67.05,5.0,4.684721,0,0,0,0,0,1,1,1,0
17728,38000,22.54,1396.0,88.76,5.0,5.458819,0,0,1,0,0,0,1,1,0
7293,70123,19.10,1197.0,85.80,9.0,4.684721,0,0,0,0,0,1,1,1,0
17673,66000,22.77,1498.0,98.59,8.0,5.858258,0,0,1,0,0,0,1,1,0

In [36]:
X_test

,km_driven,mileage,engine,max_power,age,make,Individual,Trustmark Dealer,Diesel,Electric,LPG,Petrol,Manual,5,>5
3386,60000,15.00,1586.0,104.68,13.0,4.684721,0,0,0,0,0,1,1,1,0
11664,27120,23.84,1199.0,84.00,5.0,4.381194,0,0,0,0,0,1,1,1,0
7327,48000,15.04,2755.0,174.50,4.0,10.532763,1,0,1,0,0,0,0,0,1
17993,26000,15.90,1496.0,120.69,6.0,5.858258,0,0,0,0,0,1,1,1,0
19419,59962,18.00,1198.0,86.70,8.0,5.979902,0,0,0,0,0,1,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5241,98000,21.40,1197.0,83.10,7.0,4.684721,0,0,0,0,0,1,0,1,0
3172,78245,16.10,796.0,37.00,15.0,4.684721,0,0,0,0,0,1,1,0,0
18409,19000,21.72,1498.0,108.60,5.0,7.182097,0,0,1,0,0,0,0,1,0
4699,61000,20.88,1196.0,61.70,8.0,4.684721,0,0,0,0,0,0,1,1,0
1033,70000,14.00,2523.0,75.00,9.0,7.315421,1,0,1,0,0,0,1,0,1

In [37]:
y_test

3386      2.6000
11664     4.6000
7327     20.9025
17993     7.2500
19419     3.8900
          ...
5241      5.7500
3172      0.5000
18409     9.6000
4699      3.9000
1033      6.5000
Name: selling_price, Length: 3964, dtype: float64

In [38]:
y_train

19738    9.45
17034    7.00
17080    7.85
7420     3.50
15375    8.50
         ...
9372     4.00
7291     4.70
17728    8.75
7293     4.45
17673    7.75
Name: selling_price, Length: 15856, dtype: float64

In [39]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train, y_train)

LinearRegression()

In [45]:
lr.coef_

array([-5.44228049e-06, -1.06038455e-01,  2.48917219e-04,  3.12298214e-02,
       -5.43765388e-01,  4.89599119e-01, -2.55968469e-01, -3.59686953e-01,
        6.46391075e-01,  7.25978485e+00,  2.56018700e-01, -8.38204200e-01,
       -1.66701751e+00,  6.69976670e-02,  4.75724542e-01])

In [47]:
lr.intercept_

8.313624486655765

In [51]:
y_pred = lr.predict(X_test)

In [52]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.8324107286851867

In [53]:
X_train.columns

Index(['km_driven', 'mileage', 'engine', 'max_power', 'age', 'make',
       'Individual', 'Trustmark Dealer', 'Diesel', 'Electric', 'LPG', 'Petrol',
       'Manual', '5', '>5'],
      dtype='object')

In [57]:
lr.predict([[123544, 12.3, 3094, 65, 10, 17.177585, 1, 1, 1, 0, 0, 0, 0, 0, 1]])

C:\Users\SHOYEB ANSARI\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([12.61601545])

In [59]:
import pickle
pickle_out = open("lr.pkl", "wb")
pickle.dump(lr, pickle_out)
pickle_out.close()

In [2]:
import streamlit